language: php
php:
  - 5.5
  - 5.4
before_install:
  - sudo apt-get update -qq
install:
  # PHP-CLI, Git & NodeJS are pre-installed, no need to include them
  - sudo apt-get install -y pylint python-poster
  - npm install jasmine-node
before_script:
  - make dev
script: ./run-tests --full-output
