language: php
php:
  - 7.0
  - 5.6
  - 5.5
before_install:
  - sudo apt-get update -qq
install:
  # PHP-CLI, Git & NodeJS are pre-installed, no need to include them
  # PyYaml needed for the real 'make-zip' script
  - sudo apt-get install -y python-requests python-yaml
  - npm install --global jasmine-node
  # Pylint from pip to ensure the same version as deployed
  - sudo apt-get install -y python-virtualenv
before_script:
  # Install the virtualenv and configure the IDE to use it
  - make lint-venv
  - echo "python.path = $(which python)" > config/automagic.ini
  - echo "pylint.path = $PWD/lint-venv/bin/pylint" >> config/automagic.ini
  # Create the other necessary folders
  - make dev
  # Check the config
  - cat config/automagic.ini
script: ./run-tests --full-output
