version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1

    steps:
      - checkout

      # Dependencies
      - run: sudo apt install python-virtualenv
      - run: make lint-venv
      - run: lint-venv/bin/python --version

      # Config
      - run:
          name: Create Config
          command: |
            . lint-venv/bin/activate
            make config
            cat config/automagic.ini

      # Tests
      - run: ./run-tests --full-output
