version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1

    steps:
      - checkout

      # Dependencies
      - run:
          name: Linting Virtualenv
          command: |
            sudo apt install python-virtualenv
            make lint-venv
            lint-venv/bin/python --version

      - run: sudo docker-php-ext-install pcntl

      # Config
      - run:
          name: Create Config
          command: |
            . lint-venv/bin/activate
            make config
            cat config/automagic.ini

      # Tests
      - run: ./run-tests --full-output
