version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1

    steps:
      - checkout

      # Dependencies
      - run: make lint-venv

      # Config
      - run: make config

      # Tests
      - run: ./run-tests --full-output
