version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-python-2
      - test-python-3-development

jobs:
  test-python-2:
    docker:
      - image: circleci/php:7.2-node

    steps:
      - checkout

      # Dependencies
      - run:
          name: Python things
          command: |
            sudo apt update
            sudo apt install python-requests python-virtualenv python-yaml
            make lint-venv
            lint-venv/bin/python --version

      - run: sudo npm install --global jasmine-node
      - run:
          name: PHP things
          command: |
            sudo apt install libpng-dev
            sudo docker-php-ext-install gd pcntl

      # Config
      - run:
          name: Create Config
          command: |
            . lint-venv/bin/activate
            make config
            cat config/automagic.ini

      - run:
          name: Create Test Config
          command: |
            echo 'URL = "http://localhost:8000/"' > tests/http/localconfig.py

      # Local Setup
      - run: make dev

      # Tests
      - run:
          name: Run Tests
          command: |
            php -S localhost:8000 2> server-log.txt &
            server_pid=$!
            trap "kill -SIGINT $server_pid" exit INT TERM
            ./run-tests --full-output

  # Validate that the IDE can be used to develop Python 3 code
  test-python-3-development:
    docker:
      - image: circleci/php:7.2-node

    steps:
      - checkout

      # Dependencies
      - run:
          name: Python things
          command: |
            sudo apt update
            sudo apt install python-requests python3-venv python-yaml
            python3 -m venv lint-venv
            lint-venv/bin/pip install -r pylint-requirements.txt
            lint-venv/bin/python --version

      - run: sudo npm install --global jasmine-node
      - run:
          name: PHP things
          command: |
            sudo apt install libpng-dev
            sudo docker-php-ext-install gd pcntl

      # Config
      - run:
          name: Create Config
          command: |
            . lint-venv/bin/activate
            make config
            cat config/automagic.ini

      - run:
          name: Create Test Config
          command: |
            echo 'URL = "http://localhost:8000/"' > tests/http/localconfig.py

      # Local Setup
      - run: make dev

      # Tests
      - run:
          name: Run Tests
          command: |
            php -S localhost:8000 2> server-log.txt &
            server_pid=$!
            trap "kill -SIGINT $server_pid" exit INT TERM
            ./run-tests --full-output
