version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node

    steps:
      - checkout

      # Dependencies
      - run:
          name: Python things
          command: |
            sudo apt install python-virtualenv python-yaml
            make lint-venv
            lint-venv/bin/python --version

      - run: sudo npm install --global jasmine-node
      - run: sudo docker-php-ext-install pcntl

      # Config
      - run:
          name: Create Config
          command: |
            . lint-venv/bin/activate
            make config
            cat config/automagic.ini

      # Local Setup
      - run: make dev

      # Tests
      - run: ./run-tests --full-output
